# Generated by Django 4.0.2 on 2022-02-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('skin care', 'Skin Care'), ('body care', 'Body Care'), ('makeup', 'Makeup'), ('hair care', 'Hair Care'), ('nail care', 'Nail Care'), ('fragrance', 'Fragrance'), ('tools, devices and accessories', 'Tools, Devices and Accessories')], default='others', max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('pricing_unit', models.CharField(max_length=60)),
                ('number_in_stock', models.IntegerField(null=True)),
                ('commodity_main_image', models.ImageField(default='images/commodities/main.jpg', upload_to='images/commodities')),
                ('commodity_extra_image1', models.ImageField(default='images/commodities/extra1.jpg', null=True, upload_to='images/commodities')),
                ('commodity_extra_image2', models.ImageField(default='images/commodities/extra2.jpg', null=True, upload_to='images/commodities')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('service_cost', models.FloatField()),
                ('service_estimate_time', models.FloatField()),
                ('service_main_image', models.ImageField(default='images/services/main.jpg', upload_to='images/commodities')),
                ('service_extra_image1', models.ImageField(default='images/services/extra1.jpg', null=True, upload_to='images/commodities')),
                ('service_extra_image2', models.ImageField(default='images/services/extra2.jpg', null=True, upload_to='images/commodities')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=25)),
                ('specialization', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glamourhaven.client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glamourhaven.service')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glamourhaven.employee')),
            ],
        ),
    ]
