# Generated by Django 4.0.2 on 2022-02-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourhaven', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='glamourhaven.Service'),
        ),
    ]
