# Generated by Django 4.0.2 on 2022-02-24 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glamourhaven', '0003_employee_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=12, null=True)),
                ('TransID', models.CharField(blank=True, max_length=12, null=True)),
                ('TransTime', models.CharField(blank=True, max_length=14, null=True)),
                ('TransAmount', models.CharField(blank=True, max_length=12, null=True)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=6, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=12, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=20, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=12, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('MerchantRequestID', models.CharField(blank=True, max_length=20, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=120, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(blank=True, max_length=12, null=True)),
                ('TransactionDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_extra_image1',
            field=models.ImageField(null=True, upload_to='images/commodities'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_extra_image2',
            field=models.ImageField(null=True, upload_to='images/commodities'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_main_image',
            field=models.ImageField(upload_to='images/commodities'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/profile'),
        ),
        migrations.CreateModel(
            name='LNMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('order_value', models.FloatField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=15, null=True)),
                ('order_items', models.ManyToManyField(to='glamourhaven.Commodity')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glamourhaven.lnmonline')),
                ('placer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glamourhaven.client')),
            ],
        ),
    ]
