# Generated by Django 4.0.2 on 2022-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamourhaven', '0004_c2bpayment_lnmonline_client_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_service_cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
