const AdminAddServiceList = [
  {
    id: 1,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 2,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 3,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 4,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 5,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 6,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
  {
    id: 7,
    commodity_main_image: "https://bit.ly/2Z4KKcF",
    service: "MANICURE",
    description: "text",
    duration: "50 mins",
    price: 50,
  },
];
export default AdminAddServiceList;
